version: '3'
services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  redis_cache:
    container_name: redis
    depends_on:
      - wordpress
    build: ./requirements/bonus_services/redis_cache
    restart: on-failure
    networks:
      - inception

  ftp_server:
    container_name: vsftpd
    depends_on:
      - wordpress
    build:
      context: ./requirements/bonus_services/ftp_server
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    restart: on-failure
    ports:
      - 21:21
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    build: ./requirements/bonus_services/adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus_services/cadvisor
    restart: on-failure
    ports:
      - 4242:4242
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception

volumes:
  wordpress:
  mariadb:

networks:
  inception:
    driver: bridge
