services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        SSL_C: ${SSL_C}
        SSL_ST: ${SSL_ST}
        SSL_O: ${SSL_O}
        DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASS: ${MYSQL_PASS}
    restart: on-failure
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress_volume
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb_volume

networks:
  inception:
    driver: bridge
