version: '3.3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        SSL_C: ${SSL_C}
        SSL_ST: ${SSL_ST}
        SSL_O: ${SSL_O}
        DOMAIN_NAME: ${DOMAIN_NAME}
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASS: ${MYSQL_PASS}
    restart: on-failure
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception

  redis_cache:
    container_name: redis_cache
    depends_on:
      - wordpress
    build: ./requirements/bonus_services/redis_cache
    restart: on-failure
    networks:
      - inception

  ftp_server:
    container_name: ftp_server
    depends_on:
      - wordpress
    build:
      context: ./requirements/bonus_services/ftp_server
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    restart: on-failure
    ports:
      - "21:21"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception

  static_website:
    container_name: static_website
    build: ./requirements/bonus_services/static_website
    restart: on-failure
    ports:
     - "5500:80"
    networks:
      - inception

  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    build: ./requirements/bonus_services/adminer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus_services/cadvisor
    restart: on-failure
    ports:
      - "4242:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress_volume
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb_volume

networks:
  inception:
    driver: bridge
