version: '3.3'
services:
  # nginx:
  #   container_name: 42-nginx
  #   build: ./requirements/nginx
  #   ports:
  #     - "443:443"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    networks:
      - inception
    # env_file:
    #   - .env
    # volumes:
    #   - mariadb:/var/lib/mysql

networks:
  inception:
    driver: bridge
